FROM python:3.12-slim
WORKDIR /base
COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-root --no-dev
COPY . .
WORKDIR /base/src/connector-api
ENV PYTHONPATH=/base/src
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
