# _CLOUD_SQL_INSTANCE_NAME = your cloud sql instance name
# _BACKEND_SERVICE_NAME = the name of your service - pypiserver in this case
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'BUILD IMAGE BY KANIKO'
  args: [
        '--destination=eu.gcr.io/${_PROJECT_ID}/${_BACKEND_SERVICE_NAME}',
        '--cache=true',
        '--cache-ttl=24h'
  ]
  waitFor: ['-']
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'DEPLOY YOUR SOURCE IN RUN'
  args: ['run', 'deploy', '${_BACKEND_SERVICE_NAME}',
        '--image', 'eu.gcr.io/${_PROJECT_ID}/${_BACKEND_SERVICE_NAME}',
        '--platform','managed',
        '--allow-unauthenticated',
        '--region','${_REGION}',
        '--project','${PROJECT_ID}',
        '--add-cloudsql-instances', '${_CLOUD_SQL_INSTANCE_NAME}',
        ]
  waitFor:
  - 'BUILD IMAGE BY KANIKO'
